---

install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -qq oracle-java8-installer'
  - 'sudo update-java-alternatives -s java-8-oracle'
  - 'sudo pip install html5validator'

script:
  - "make check"
